version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hrloop-app
    volumes:
      - .:/var/www
    networks:
      - hrloop
    depends_on:
      - db
      - redis

  web:
    image: nginx:alpine
    container_name: hrloop-web
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - hrloop
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: hrloop-db
    environment:
      MYSQL_DATABASE: hrloop
      MYSQL_ROOT_PASSWORD: supersecretroot
      MYSQL_USER: hrloop_user
      MYSQL_PASSWORD: hrloop_pass
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - hrloop

  redis:
    image: redis:alpine
    container_name: hrloop-redis
    command: redis-server --appendonly yes --requirepass secret
    networks:
      - hrloop

networks:
  hrloop:

volumes:
  dbdata:
